import "./List.css";
import React, { useState, useEffect } from "react";
import axios from "axios";

const List = ({ username, idToken }) => {
  const [windowResizeEventListener, setEventListener] = useState(null);
  const [mobileMode, setMobileMode] = useState(false);
  const [urls, setUrls] = useState([]);
  const [refreshUrls, setRefreshUrls] = useState(false);
  useEffect(() => {
    setEventListener(
      window.addEventListener("resize", () => {
        if (window.innerWidth < 768) {
          setMobileMode(true);
        } else {
          setMobileMode(false);
        }
      })
    );
    return () => {
      window.removeEventListener("resize", windowResizeEventListener);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  useEffect(() => {
    axios.get(`/api/${username}`).then((res) => {
      let finalList = [];
      res.data.shortUrls.forEach(({ short, full, clicks, _id }) => {
        finalList.push({
          short,
          full,
          clicks,
          id: _id,
        });
      });
      setUrls(finalList);
    });
  }, [username, refreshUrls]);
  const deleteUrlFromList = (id, idx) => {
    const decision = window.confirm("Confirm delete ?");
    if (decision) {
      axios.delete(`/api/short/${id}`, {
        data: {
          idToken,
          username,
        },
      });
      setUrls((prev) => {
        let temp = [...prev];
        temp.splice(idx, 1);
        return temp;
      });
    }
  };
  return (
    <div className="list-container">
      <p>List of all links generated by you</p>
      <p onClick={() => setRefreshUrls((prev) => !prev)}>Refresh list</p>
      <div className="list">
        <div className="list-item">
          <span className="column-1">Short URL</span>
          <span className="column-2">FULL URL</span>
          <span className="column-3">Clicks</span>
        </div>
        {urls.length === 0 ? <div>'No data'</div> : null}
        {urls.map((url, idx) => (
          <div className="list-item" key={url.id}>
            <a
              className="column-1"
              target="_blank"
              rel="noreferrer"
              href={window.location.href + url.short}
            >
              {window.location.href + url.short}
            </a>
            <a
              className="column-2"
              target="_blank"
              rel="noreferrer"
              href={url.full}
            >
              {url.full.slice(0, mobileMode ? 35 : 50) + "..."}
            </a>
            <span className="column-3">{url.clicks}</span>
            <span
              onClick={() => deleteUrlFromList(url.id, idx)}
              className="column-4"
            >
              Delete
            </span>
          </div>
        ))}
      </div>
    </div>
  );
};

export default List;
