import "./List.css";
import React, { useState, useEffect } from "react";
import axios from "axios";

const List = ({ username, idToken, mobileMode }) => {
  const [urls, setUrls] = useState([]);
  const [refreshUrls, setRefreshUrls] = useState(false);
  useEffect(() => {
    axios.get(`/api/${username}`).then((res) => {
      let finalList = [];
      res.data.shortUrls.forEach(({ short, full, clicks, _id }) => {
        finalList.push({
          short,
          full,
          clicks,
          id: _id,
        });
      });
      setUrls(finalList);
    });
  }, [username, refreshUrls]);
  const deleteUrlFromList = (id, idx) => {
    const decision = window.confirm("Confirm delete ?");
    if (decision) {
      axios.delete(`/api/short/${id}`, {
        data: {
          idToken,
          username,
        },
      });
      setUrls((prev) => {
        let temp = [...prev];
        temp.splice(idx, 1);
        return temp;
      });
    }
  };
  return (
    <div className="list-container">
      <p>Last 5 links generated by you</p>
      <p onClick={() => setRefreshUrls((prev) => !prev)}>Refresh list</p>
      <div className="list">
        <table>
          <tr>
            <th>Short URL</th>
            <th>FULL URL</th>
            <th>Clicks</th>
          </tr>
          {urls.length === 0 ? <div>'No data'</div> : null}
          {urls.map((url, idx) => (
            <tr>
              <td>
                <a
                  className="column-1"
                  target="_blank"
                  rel="noreferrer"
                  href={window.location.href + url.short}
                >
                  {url.short}
                </a>
              </td>
              <td>
                <a
                  className="column-2"
                  target="_blank"
                  rel="noreferrer"
                  href={url.full}
                >
                  {url.full.slice(0, mobileMode ? 35 : 50) + "..."}
                </a>
              </td>
              <td>{url.clicks}</td>
              <td onClick={() => deleteUrlFromList(url.id, idx)}>
                <p className="td-delete">Delete</p>
              </td>
            </tr>
          ))}
        </table>
      </div>
    </div>
  );
};

export default List;
